<?php
require_once __DIR__.'/includes/auth.php'; $u=require_role('customer');
$target=(int)($_GET['provider']??$_POST['target_id']??0); $kind=$_GET['type']??$_POST['target_type']??'provider';
if(!in_array($kind,['provider','business'],true)) $kind='provider';
$t=null;if($target){$s=db()->prepare("SELECT id,name,role,status,city,area FROM users WHERE id=? AND role=? AND status='active'");$s->execute([$target,$kind]);$t=$s->fetch();}
if(!$t){flash('error','The selected provider or business is unavailable.');redirect('search.php');}
$cats=db()->query("SELECT id,name FROM categories WHERE is_active=1 ORDER BY name")->fetchAll();
$sv=db()->prepare("SELECT s.id,s.category_id,s.name FROM provider_services ps JOIN services s ON s.id=ps.service_id WHERE ps.provider_user_id=? AND ps.is_active=1 AND s.is_active=1 ORDER BY s.name");$sv->execute([$target]);$services=$sv->fetchAll();
$err=[];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$cat=(int)($_POST['category_id']??0);$sid=(int)($_POST['service_id']??0);$title=trim((string)($_POST['title']??''));$desc=trim((string)($_POST['description']??''));$loc=trim((string)($_POST['location_text']??''));$notes=trim((string)($_POST['additional_notes']??''));try{$date=nullable_date($_POST['preferred_date']??null,false,'Preferred date');$time=nullable_time($_POST['preferred_time']??null,'Preferred time');$bmin=nullable_money($_POST['budget_min']??null,'Minimum budget');$bmax=nullable_money($_POST['budget_max']??null,'Maximum budget');}catch(RuntimeException $e){$err[]=$e->getMessage();$date=$time=$bmin=$bmax=null;}
if(!$cat)$err[]='Please select a service category.';if(!$sid)$err[]='Please select a service.';if($title==='')$err[]='Please enter the required service.';elseif(text_length($title)>180)$err[]='Service title is too long.';if($desc==='')$err[]='Please describe the problem.';elseif(text_length($desc)>10000)$err[]='Description is too long.';if($loc==='')$err[]='Please enter the service location.';elseif(text_length($loc)>255)$err[]='Service location is too long.';if(text_length($notes)>5000)$err[]='Additional notes are too long.';
$ok=false;foreach($services as $x)if((int)$x['id']===$sid&&(int)$x['category_id']===$cat)$ok=true;if(!$ok)$err[]='That service is not offered by this provider.';if($bmin!==null&&$bmax!==null&&$bmin>$bmax)$err[]='Minimum budget cannot exceed maximum budget.';
if(!$err){$pdo=db();$pdo->beginTransaction();try{$q=$pdo->prepare("INSERT INTO service_requests(customer_id,provider_id,business_id,category_id,service_id,request_type,title,description,location_text,preferred_date,preferred_time,budget_min,budget_max,additional_notes,status) VALUES(?,?,?,?,?,'direct',?,?,?,?,?,?,?,?, 'pending')");$q->execute([$u['id'],$kind==='provider'?$target:null,$kind==='business'?$target:null,$cat,$sid,$title,$desc,$loc,$date,$time,$bmin,$bmax,$notes?:null]);$id=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO request_status_history(request_id,status,changed_by,note) VALUES(?,'pending',?,'Service request submitted')")->execute([$id,$u['id']]);$pdo->prepare("INSERT INTO notifications(user_id,type,title,message,link) VALUES(?,'service_request','New service request',?,?)")->execute([$target,$u['name'].' sent you a service request.','request-details.php?id='.$id]);$pdo->commit();flash('success','Service request submitted successfully.');redirect('customer/requests.php');}catch(Throwable $e){$pdo->rollBack();$err[]='Could not submit the request. Please try again.';}}
}
$pageTitle='Request Service — LocalConnect';require __DIR__.'/includes/header.php';?>
<div class="container py-5" style="max-width:900px"><a href="<?=e(base_url($kind.'.php?id='.$target))?>" class="text-decoration-none">&larr; Back to profile</a><div class="soft-card p-4 p-md-5 mt-3"><h1 class="h3 fw-bold">Request service from <?=e($t['name'])?></h1><p class="text-muted">Your request will be saved and sent directly to this <?=e($kind)?>.</p><?php foreach($err as $x):?><div class="alert alert-danger"><?=e($x)?></div><?php endforeach;?>
<form method="post" class="row g-3"><?=csrf_field()?><input type="hidden" name="target_id" value="<?=$target?>"><input type="hidden" name="target_type" value="<?=e($kind)?>"><div class="col-md-6"><label class="form-label">Category *</label><select name="category_id" id="category" class="form-select" data-service-filter="#service" required><option value="">Select category</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=((int)($_POST['category_id']??0)==$c['id'])?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label">Service *</label><select name="service_id" id="service" class="form-select" required><option value="">Select service</option><?php foreach($services as $s):?><option data-category="<?=$s['category_id']?>" value="<?=$s['id']?>" <?=((int)($_POST['service_id']??0)==$s['id'])?'selected':''?>><?=e($s['name'])?></option><?php endforeach;?></select></div><div class="col-12"><label class="form-label">Required service *</label><input name="title" class="form-control" maxlength="180" required value="<?=e($_POST['title']??'')?>"></div><div class="col-12"><label class="form-label">Description / problem *</label><textarea name="description" class="form-control" rows="4" required><?=e($_POST['description']??'')?></textarea></div><div class="col-12"><label class="form-label">Service location *</label><input name="location_text" class="form-control" required value="<?=e($_POST['location_text']??trim(($u['area']??'').', '.($u['city']??''),', '))?>"></div><div class="col-md-6"><label class="form-label">Preferred date</label><input type="date" name="preferred_date" class="form-control" min="<?=date('Y-m-d')?>" value="<?=e($_POST['preferred_date']??'')?>"></div><div class="col-md-6"><label class="form-label">Preferred time</label><input type="time" name="preferred_time" class="form-control" value="<?=e($_POST['preferred_time']??'')?>"></div><div class="col-md-6"><label class="form-label">Budget min (₹)</label><input type="number" min="0" step="1" name="budget_min" class="form-control" value="<?=e($_POST['budget_min']??'')?>"></div><div class="col-md-6"><label class="form-label">Budget max (₹)</label><input type="number" min="0" step="1" name="budget_max" class="form-control" value="<?=e($_POST['budget_max']??'')?>"></div><div class="col-12"><label class="form-label">Additional notes</label><textarea name="additional_notes" class="form-control" rows="2"><?=e($_POST['additional_notes']??'')?></textarea></div><div class="col-12"><button class="btn btn-primary btn-lg">Send Service Request</button></div></form></div></div><?php require __DIR__.'/includes/footer.php';?>