<?php
require_once __DIR__.'/includes/auth.php';
$u=require_login();$pageTitle='Reviews — LocalConnect';
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    if($u['role']!=='customer'){http_response_code(403);include __DIR__.'/403.php';exit;}
    $requestId=(int)($_POST['request_id']??0);$rating=(int)($_POST['rating']??0);$comment=trim((string)($_POST['comment']??''));
    if(text_length($comment)>2000){flash('error','Review comment is too long.');redirect('reviews.php');}
    if($rating<1||$rating>5){flash('error','Please choose a rating from 1 to 5 stars.');redirect('reviews.php');}
    $q=db()->prepare("SELECT id,provider_id,business_id FROM service_requests WHERE id=? AND customer_id=? AND status='completed' LIMIT 1");$q->execute([$requestId,$u['id']]);$r=$q->fetch();
    if(!$r){flash('error','You can review only your own completed service request.');redirect('reviews.php');}
    $target=(int)($r['provider_id']?:$r['business_id']);if(!$target){flash('error','This request has no service provider to review.');redirect('reviews.php');}
    try{$pdo=db();$pdo->beginTransaction();$pdo->prepare("INSERT INTO reviews(request_id,customer_id,target_user_id,rating,comment) VALUES(?,?,?,?,?)")->execute([$requestId,$u['id'],$target,$rating,$comment?:null]);$pdo->prepare("INSERT INTO notifications(user_id,type,title,message,link) VALUES(?,'new_review','You received a new review',?,'reviews.php')")->execute([$target,'A customer left a '.$rating.'-star review.']);$pdo->commit();flash('success','Thank you. Your review has been published.');}
    catch(PDOException $e){if(db()->inTransaction())db()->rollBack();flash('error','A review for this service request already exists.');}
    redirect('reviews.php');
}
$success=flash('success');$error=flash('error');$pg=pagination_window(20,40);$eligible=[];$mine=[];$received=[];$hasNext=false;
if($u['role']==='customer'){
    $q=db()->prepare("SELECT sr.id,sr.title,sr.updated_at completed_at,COALESCE(p.name,b.name) target_name FROM service_requests sr LEFT JOIN users p ON p.id=sr.provider_id LEFT JOIN users b ON b.id=sr.business_id LEFT JOIN reviews v ON v.request_id=sr.id WHERE sr.customer_id=? AND sr.status='completed' AND v.id IS NULL ORDER BY sr.updated_at DESC,sr.id DESC LIMIT 10");$q->execute([(int)$u['id']]);$eligible=$q->fetchAll();
    $q=db()->prepare("SELECT v.id,v.request_id,v.rating,v.comment,v.status,v.created_at,r.title,u.name target_name FROM reviews v JOIN service_requests r ON r.id=v.request_id JOIN users u ON u.id=v.target_user_id WHERE v.customer_id=? ORDER BY v.created_at DESC,v.id DESC LIMIT ".($pg['per']+1)." OFFSET ".$pg['offset']);$q->execute([(int)$u['id']]);$mine=$q->fetchAll();$hasNext=trim_page_results($mine,$pg['per']);
}elseif(in_array($u['role'],['provider','business'],true)){
    $q=db()->prepare("SELECT v.id,v.request_id,v.rating,v.comment,v.created_at,r.title,c.name customer_name FROM reviews v JOIN service_requests r ON r.id=v.request_id JOIN users c ON c.id=v.customer_id WHERE v.target_user_id=? AND v.status='published' ORDER BY v.created_at DESC,v.id DESC LIMIT ".($pg['per']+1)." OFFSET ".$pg['offset']);$q->execute([(int)$u['id']]);$received=$q->fetchAll();$hasNext=trim_page_results($received,$pg['per']);
}
release_session_lock();
require __DIR__.'/includes/header.php';?>
<div class="container py-5" style="max-width:1000px"><h1 class="fw-bold mb-4">Reviews & Ratings</h1><?php if($success):?><div class="alert alert-success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<?php if($u['role']==='customer'):?><div class="soft-card p-4 mb-4"><h2 class="h5">Services ready to review</h2><?php if(!$eligible):?><p class="text-muted mb-0">No completed services are waiting for a review.</p><?php endif;?><?php foreach($eligible as $x):?><form method="post" class="border-top pt-3 mt-3"><?=csrf_field()?><input type="hidden" name="request_id" value="<?=$x['id']?>"><strong><?=e($x['title'])?></strong><div class="small text-muted mb-2">Provided by <?=e($x['target_name'])?></div><div class="row g-2"><div class="col-md-3"><select class="form-select" name="rating" required><option value="">Rating</option><?php for($i=5;$i>=1;$i--):?><option value="<?=$i?>"><?=$i?> star<?=$i>1?'s':''?></option><?php endfor;?></select></div><div class="col-md-7"><input class="form-control" name="comment" maxlength="2000" placeholder="Share your experience (optional)"></div><div class="col-md-2"><button class="btn btn-primary w-100">Submit</button></div></div></form><?php endforeach;?></div>
<div class="soft-card p-4"><h2 class="h5">Your review history</h2><?php if(!$mine):?><p class="text-muted mb-0">You have not posted reviews on this page.</p><?php endif;?><?php foreach($mine as $x):?><div class="border-top py-3"><strong><?=e($x['target_name'])?></strong><span class="text-warning ms-2"><?=str_repeat('★',(int)$x['rating'])?></span><div class="small text-muted"><?=e($x['title'])?> · <?=e(date('d M Y',strtotime($x['created_at'])))?></div><?php if($x['comment']):?><p class="mb-0 mt-1"><?=e($x['comment'])?></p><?php endif;?></div><?php endforeach;?><?=pagination_nav($pg['page'],$hasNext)?></div>
<?php else:?><div class="soft-card p-4"><h2 class="h5">Reviews received</h2><?php $sum=rating_summary((int)$u['id']);?><div class="display-6 fw-bold"><?=number_format((float)$sum['avg_rating'],1)?> <span class="text-warning fs-4">★</span></div><p class="text-muted"><?=$sum['total']?> published reviews</p><?php if(!$received):?><p class="text-muted mb-0">No reviews received on this page.</p><?php endif;?><?php foreach($received as $x):?><div class="border-top py-3"><strong><?=e($x['customer_name'])?></strong><span class="text-warning ms-2"><?=str_repeat('★',(int)$x['rating'])?></span><div class="small text-muted"><?=e($x['title'])?> · <?=e(date('d M Y',strtotime($x['created_at'])))?></div><?php if($x['comment']):?><p class="mb-0 mt-1"><?=e($x['comment'])?></p><?php endif;?></div><?php endforeach;?><?=pagination_nav($pg['page'],$hasNext)?></div><?php endif;?></div><?php require __DIR__.'/includes/footer.php';?>
