<?php
require_once __DIR__.'/includes/auth.php';
$q=trim($_GET['q']??'');$location=trim($_GET['location']??'');$category=(int)($_GET['category']??0);$type=$_GET['type']??'';$availability=$_GET['availability']??'';$sort=$_GET['sort']??'rating';$maxPrice=(float)($_GET['max_price']??0);$pg=pagination_window(24,48);release_session_lock();
$sql="SELECT u.id,u.name,u.role,u.profile_image,u.city,u.state,u.area,pp.headline,pp.service_area,pp.price_min,pp.price_max,pp.availability_status,pp.verification_status,bp.business_name,bp.logo,bp.description,bp.price_min bmin,bp.price_max bmax,bp.verification_status bverify,COALESCE(AVG(r.rating),0) avg_rating,COUNT(DISTINCT r.id) review_count
FROM users u
LEFT JOIN provider_profiles pp ON pp.user_id=u.id
LEFT JOIN business_profiles bp ON bp.user_id=u.id
LEFT JOIN provider_services ps ON ps.provider_user_id=u.id AND ps.is_active=1
LEFT JOIN services s ON s.id=ps.service_id
LEFT JOIN reviews r ON r.target_user_id=u.id AND r.status='published'
WHERE u.status='active' AND u.role IN ('provider','business')";$p=[];
if($q!==''){$sql.=" AND (u.name LIKE ? OR pp.headline LIKE ? OR bp.business_name LIKE ? OR s.name LIKE ? OR ps.title LIKE ?)";$like='%'.$q.'%';array_push($p,$like,$like,$like,$like,$like);}
if($location!==''){$sql.=" AND (u.city LIKE ? OR u.area LIKE ? OR pp.service_area LIKE ? OR bp.address LIKE ?)";$like='%'.$location.'%';array_push($p,$like,$like,$like,$like);}
if($category){$sql.=" AND (s.category_id=? OR bp.category_id=?)";array_push($p,$category,$category);}
if(in_array($type,['provider','business'],true)){$sql.=" AND u.role=?";$p[]=$type;}
if($availability==='available'){$sql.=" AND (u.role='business' OR pp.availability_status='available')";}
if($maxPrice>0){$sql.=" AND ((u.role='provider' AND (pp.price_min IS NULL OR pp.price_min<=?)) OR (u.role='business' AND (bp.price_min IS NULL OR bp.price_min<=?)))";$p[]=$maxPrice;$p[]=$maxPrice;}
$order=match($sort){'reviews'=>'review_count DESC,avg_rating DESC,u.id DESC','price'=>'COALESCE(pp.price_min,bp.price_min,999999999) ASC,u.id DESC','newest'=>'u.created_at DESC,u.id DESC',default=>'avg_rating DESC,review_count DESC,u.id DESC'};
$sql.=" GROUP BY u.id ORDER BY $order LIMIT ".($pg['per']+1)." OFFSET ".$pg['offset'];$st=db()->prepare($sql);$st->execute($p);$results=$st->fetchAll();$hasNext=trim_page_results($results,$pg['per']);$cats=db()->query("SELECT id,name FROM categories WHERE is_active=1 ORDER BY name LIMIT 250")->fetchAll();
$pageTitle='Find Local Services — LocalConnect';require __DIR__.'/includes/header.php';?>
<div class="container py-5"><h1 class="fw-bold mb-4">Find local services</h1><form class="soft-card p-3 mb-4" method="get"><div class="row g-2"><div class="col-lg-3"><input class="form-control" name="q" value="<?=e($q)?>" placeholder="Service or keyword"></div><div class="col-lg-2"><input class="form-control" name="location" value="<?=e($location)?>" placeholder="City / area"></div><div class="col-lg-3"><select class="form-select" name="category"><option value="">All categories</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=$category===$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select></div><div class="col-lg-2"><select class="form-select" name="type"><option value="">All providers</option><option value="provider" <?=$type==='provider'?'selected':''?>>Workers</option><option value="business" <?=$type==='business'?'selected':''?>>Businesses</option></select></div><div class="col-lg-2 d-grid"><button class="btn btn-primary"><i class="fa fa-search me-1"></i> Search</button></div><div class="col-lg-2"><select class="form-select" name="availability"><option value="">Any availability</option><option value="available" <?=$availability==='available'?'selected':''?>>Available now</option></select></div><div class="col-lg-2"><input class="form-control" type="number" min="0" name="max_price" value="<?=$maxPrice?:''?>" placeholder="Max price ₹"></div><div class="col-lg-2"><select class="form-select" name="sort"><option value="rating" <?=$sort==='rating'?'selected':''?>>Rating</option><option value="reviews" <?=$sort==='reviews'?'selected':''?>>Most reviewed</option><option value="price" <?=$sort==='price'?'selected':''?>>Price</option><option value="newest" <?=$sort==='newest'?'selected':''?>>Newest</option></select></div></div></form>
<p class="text-muted">Showing <?=count($results)?> result(s) on page <?=$pg['page']?>. Location shown is the provider's selected city/service area; no fake distance is calculated.</p><div class="row g-4"><?php foreach($results as $r):$name=$r['role']==='business'?($r['business_name']?:$r['name']):$r['name'];$img=$r['role']==='business'?($r['logo']?:$r['profile_image']):$r['profile_image'];$verified=$r['role']==='business'?$r['bverify']:$r['verification_status'];$min=$r['role']==='business'?$r['bmin']:$r['price_min'];$max=$r['role']==='business'?$r['bmax']:$r['price_max'];?><div class="col-md-6 col-lg-4"><div class="soft-card h-100 p-4"><div class="d-flex gap-3"><img class="profile-thumb" src="<?=e($img?base_url($img):base_url('assets/images/avatar-placeholder.svg'))?>" alt=""><div><h5 class="mb-1"><?=e($name)?> <?php if($verified==='verified'):?><span class="text-primary" title="Verified by LocalConnect"><i class="fa-solid fa-circle-check"></i></span><?php endif;?></h5><div class="small text-muted"><?=e(trim(($r['area']??'').' '.($r['city']??'').' '.($r['state']??'')))?></div><div class="small text-warning"><i class="fa fa-star"></i> <?=number_format((float)$r['avg_rating'],1)?> <span class="text-muted">(<?=$r['review_count']?>)</span></div></div></div><p class="text-muted mt-3 mb-3"><?=e($r['headline']?:($r['description']?:ucfirst($r['role'])))?></p><div class="small mb-3"><?php if($min!==null):?>₹<?=number_format((float)$min,0)?><?=$max?' – ₹'.number_format((float)$max,0):'+'?><?php else:?>Price on request<?php endif;?></div><a class="btn btn-outline-primary w-100" href="<?=e(base_url(($r['role']==='business'?'business.php':'provider.php').'?id='.$r['id']))?>">View Profile</a></div></div><?php endforeach;?><?php if(!$results):?><div class="col-12"><div class="soft-card p-5 text-center"><h4>No providers found on this page</h4><p class="text-muted">Try another service, category or location.</p><a class="btn btn-primary" href="<?=e(base_url('search.php'))?>">Search Again</a></div></div><?php endif;?></div><?=pagination_nav($pg['page'],$hasNext)?></div>
<?php require __DIR__.'/includes/footer.php';?>
