<?php
require_once __DIR__.'/../includes/auth.php';require_guest();$allowedRoles=['customer','provider','business'];$role=$_POST['role']??$_GET['role']??'customer';if(!in_array($role,$allowedRoles,true))$role='customer';$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{$name=clean_text($_POST['name']??'',120,true,'Full name');$email=strtolower(clean_text($_POST['email']??'',190,true,'Email'));$phone=clean_text($_POST['phone']??'',25,false,'Phone');$password=is_string($_POST['password']??null)?$_POST['password']:'';$confirm=is_string($_POST['confirm_password']??null)?$_POST['confirm_password']:'';$city=clean_text($_POST['city']??'',100,false,'City');$state=clean_text($_POST['state']??'',100,false,'State');if(text_length($name)<2)throw new RuntimeException('Please enter your full name.');if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Please enter a valid email address.');if(!valid_phone_or_empty($phone))throw new RuntimeException('Please enter a valid phone number.');if(strlen($password)<12)throw new RuntimeException('Password must be at least 12 characters.');if(strlen($password)>200)throw new RuntimeException('Password is too long.');if($password!==$confirm)throw new RuntimeException('Passwords do not match.');if(!in_array($role,$allowedRoles,true))throw new RuntimeException('Please select a valid account type.');}catch(RuntimeException $e){$errors[]=$e->getMessage();}
    if(!$errors){$check=db()->prepare('SELECT id FROM users WHERE email=? LIMIT 1');$check->execute([$email]);if($check->fetch())$errors[]='An account with this email already exists.';}
    if(!$errors){$pdo=db();try{$pdo->beginTransaction();$needsVerify=env_bool('APP_REQUIRE_EMAIL_VERIFICATION',is_production());$status=$needsVerify?'pending':'active';$verified=$needsVerify?null:date('Y-m-d H:i:s');$stmt=$pdo->prepare('INSERT INTO users(name,email,phone,password_hash,role,status,city,state,email_verified_at) VALUES(?,?,?,?,?,?,?,?,?)');$stmt->execute([$name,$email,$phone?:null,password_hash($password,PASSWORD_DEFAULT),$role,$status,$city?:null,$state?:null,$verified]);$uid=(int)$pdo->lastInsertId();if($role==='provider'){$s=$pdo->prepare("INSERT INTO provider_profiles(user_id,verification_status) VALUES(?,'pending')");$s->execute([$uid]);}if($role==='business'){$s=$pdo->prepare("INSERT INTO business_profiles(user_id,verification_status) VALUES(?,'pending')");$s->execute([$uid]);}$pdo->commit();log_activity($uid,'account_registered','user',$uid);
        if($needsVerify){$token=create_auth_token($uid,'email_verify',86400);$link=absolute_url('auth/verify-email.php?selector='.rawurlencode($token['selector']).'&token='.rawurlencode($token['token']));$sent=send_app_email($email,'Verify your LocalConnect email',"Open this link to verify your account:\n{$link}\n\nThis link expires in 24 hours.");flash('success',$sent?'Account created. Check your email to verify it before logging in.':'Account created, but verification email delivery is not configured. Contact the administrator.');redirect('auth/login.php');}
        session_regenerate_id(true);$_SESSION['user_id']=$uid;$_SESSION['session_version']=1;flash('success','Welcome to LocalConnect! Your account has been created.');redirect(dashboard_for($role));
    }catch(Throwable $ex){if($pdo->inTransaction())$pdo->rollBack();security_log('registration_failed',['error_class'=>$ex::class]);$errors[]='We could not create your account right now. Please try again.';}}
}
$pageTitle='Create account — LocalConnect';require __DIR__.'/../includes/header.php';?>
<div class="container auth-wrap py-5"><div class="soft-card p-4 p-md-5"><h2 class="fw-bold">Create your LocalConnect account</h2><p class="text-muted">Choose how you want to use the platform.</p><?php foreach($errors as $er):?><div class="alert alert-danger"><?=e($er)?></div><?php endforeach;?><form method="post" novalidate><?=csrf_field()?><div class="row g-3 mb-4"><?php foreach(['customer'=>['fa-user','Customer','Find and request local services'],'provider'=>['fa-screwdriver-wrench','Service Provider','Offer your skills and services'],'business'=>['fa-store','Business Owner','List and manage a local business']] as $key=>$opt):?><div class="col-md-4"><label class="soft-card role-card d-block p-3 h-100 <?= $role===$key?'active':'' ?>" data-role-option><input class="form-check-input me-2" type="radio" name="role" value="<?=e($key)?>" <?= $role===$key?'checked':'' ?>><i class="fa-solid <?=e($opt[0])?> me-1"></i><strong><?=e($opt[1])?></strong><div class="small-muted mt-2"><?=e($opt[2])?></div></label></div><?php endforeach;?></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Full name</label><input class="form-control" name="name" maxlength="120" required value="<?=e($_POST['name']??'')?>"></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="email" maxlength="190" required value="<?=e($_POST['email']??'')?>"></div><div class="col-md-6"><label class="form-label">Phone</label><input class="form-control" name="phone" maxlength="25" value="<?=e($_POST['phone']??'')?>"></div><div class="col-md-3"><label class="form-label">City</label><input class="form-control" name="city" maxlength="100" value="<?=e($_POST['city']??'')?>"></div><div class="col-md-3"><label class="form-label">State</label><input class="form-control" name="state" maxlength="100" value="<?=e($_POST['state']??'')?>"></div><div class="col-md-6"><label class="form-label">Password</label><input class="form-control" type="password" name="password" required minlength="12" maxlength="200" autocomplete="new-password"><div class="form-text">Use at least 12 characters.</div></div><div class="col-md-6"><label class="form-label">Confirm password</label><input class="form-control" type="password" name="confirm_password" required maxlength="200" autocomplete="new-password"></div></div><button class="btn btn-primary btn-lg w-100 mt-4">Create account</button></form><p class="text-center text-muted mt-3 mb-0">Already registered? <a href="<?=e(base_url('auth/login.php'))?>">Login</a></p></div></div>
<?php require __DIR__.'/../includes/footer.php'; ?>
