<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';
require_once __DIR__.'/../includes/billing.php';
$user=require_role(['provider','business']);$page=max(1,(int)($_GET['page']??1));$per=20;$offset=($page-1)*$per;
$c=db()->prepare('SELECT COUNT(*) FROM payments WHERE user_id=?');$c->execute([(int)$user['id']]);$total=(int)$c->fetchColumn();
$q=db()->prepare('SELECT p.*,s.status subscription_status,s.starts_at,s.ends_at FROM payments p LEFT JOIN subscriptions s ON s.id=p.subscription_id WHERE p.user_id=? ORDER BY p.id DESC LIMIT ? OFFSET ?');$q->bindValue(1,(int)$user['id'],PDO::PARAM_INT);$q->bindValue(2,$per,PDO::PARAM_INT);$q->bindValue(3,$offset,PDO::PARAM_INT);$q->execute();$rows=$q->fetchAll();
$pageTitle='Billing History — LocalConnect';require __DIR__.'/../includes/header.php';
?>
<div class="container py-5"><div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="fw-bold mb-1">Billing history</h1><p class="text-muted mb-0">Paid entitlement is granted only after verified reconciliation.</p></div><a class="btn btn-outline-primary" href="<?=e(base_url(($user['role']==='business'?'business':'provider').'/subscription.php'))?>">Plans</a></div><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>ID</th><th>Plan</th><th>Method</th><th>Amount</th><th>Payment</th><th>Reconciliation</th><th>Entitlement</th><th>Created</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="8" class="text-center text-muted py-4">No billing records yet.</td></tr><?php endif;?><?php foreach($rows as $r):?><tr><td>#<?=(int)$r['id']?></td><td><?=e($r['plan_name_snapshot']??'—')?></td><td><?=e($r['payment_method_name_snapshot']??'—')?></td><td>₹<?=number_format((float)$r['amount'],2)?> <?=e($r['currency'])?></td><td><span class="badge text-bg-<?=in_array($r['status'],['paid'],true)?'success':(in_array($r['status'],['failed','cancelled','refunded','disputed'],true)?'danger':'warning')?>"><?=e($r['status'])?></span></td><td><?=e($r['reconciliation_status']??'—')?><?php if($r['reconciliation_note']):?><div class="small text-muted"><?=e($r['reconciliation_note'])?></div><?php endif;?></td><td><?=e($r['subscription_status']??'Not active')?><?php if($r['starts_at']):?><div class="small text-muted"><?=e($r['starts_at'])?> → <?=e($r['ends_at']??'—')?></div><?php endif;?></td><td><?=e($r['created_at'])?><?php if(in_array($r['status'],['pending','requires_review'],true)):?><form method="post" action="<?=e(base_url('billing/cancel.php'))?>" class="mt-2"><?=csrf_field()?><input type="hidden" name="payment_id" value="<?=(int)$r['id']?>"><button class="btn btn-sm btn-outline-danger">Stop checkout</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div><?php $pages=max(1,(int)ceil($total/$per));if($pages>1):?><nav class="mt-3"><ul class="pagination"><?php for($i=1;$i<=$pages;$i++):?><li class="page-item <?=$i===$page?'active':''?>"><a class="page-link" href="?page=<?=$i?>"><?=$i?></a></li><?php endfor;?></ul></nav><?php endif;?></div>
<?php require __DIR__.'/../includes/footer.php';?>
