<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';
require_once __DIR__.'/../includes/billing.php';
$user=require_role(['provider','business']);$token=(string)($_GET['token']??$_POST['token']??'');$intent=checkout_intent($token,(int)$user['id']);
if(!$intent||$intent['status']!=='pending_manual'||empty($intent['payment_id'])){flash('error','Manual payment checkout is unavailable.');redirect('billing/history.php');}
$payment=payment_by_id((int)$intent['payment_id']);if(!$payment||(int)$payment['user_id']!==(int)$user['id']){http_response_code(404);include __DIR__.'/../404.php';exit;}
$error='';if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();try{submit_manual_payment_reference((int)$payment['id'],$user,(string)($_POST['payer_reference']??''),(string)($_POST['payer_note']??''));flash('success','Transfer reference submitted. This does not activate the plan; an administrator must reconcile the merchant account first.');redirect('billing/history.php');}catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'Reference could not be submitted.';}}
$pageTitle='Manual Payment — LocalConnect';require __DIR__.'/../includes/header.php';
?>
<div class="container py-5" style="max-width:760px"><h1 class="fw-bold">Manual payment</h1><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5"><?=e($payment['payment_method_name_snapshot'])?></h2><p><strong>Amount:</strong> ₹<?=number_format((float)$payment['amount'],2)?> <?=e($payment['currency'])?></p><?php if($payment['payment_method_type_snapshot']==='upi'):?><p><strong>Merchant UPI ID:</strong> <code><?=e($payment['merchant_upi_id_snapshot'])?></code></p><?php else:?><p><strong>Beneficiary:</strong> <?=e($payment['bank_beneficiary_snapshot'])?></p><?php if($payment['bank_reference_snapshot']):?><p><strong>Reference instruction:</strong> <?=e($payment['bank_reference_snapshot'])?></p><?php endif;?><?php endif;?><div class="alert alert-secondary" style="white-space:pre-wrap"><?=e($payment['manual_instructions_snapshot'])?></div><div class="alert alert-warning">A transaction ID/reference is only a claim. LocalConnect will keep this payment pending until an authorized administrator checks the merchant bank/UPI account and explicitly verifies it.</div><form method="post"><?=csrf_field()?><input type="hidden" name="token" value="<?=e($token)?>"><label class="form-label">Your transfer/reference ID</label><input class="form-control" name="payer_reference" maxlength="190" required><label class="form-label mt-3">Optional note</label><textarea class="form-control" name="payer_note" maxlength="500" rows="3"></textarea><button class="btn btn-primary mt-3">Submit for verification</button></form></div></div></div>
<?php require __DIR__.'/../includes/footer.php';?>
