<?php
define('LOCALCONNECT_MFA_PAGE',true);require_once __DIR__.'/../includes/auth.php';$u=require_login();if($u['role']!=='admin'){http_response_code(403);include __DIR__.'/../403.php';exit;}$uid=(int)$u['id'];$record=admin_mfa_record($uid);$error='';
function mfa_secret_from_record(array $r): string { return decrypt_sensitive((string)$r['secret_ciphertext'],(string)$r['secret_nonce'],(string)$r['encryption_alg']); }
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();$action=(string)($_POST['action']??'verify');
 try{
  if($action==='verify'){
   if(!$record)throw new RuntimeException('MFA is not configured yet.');$secret=mfa_secret_from_record($record);$step=verify_totp($secret,trim((string)($_POST['code']??'')),isset($record['last_used_step'])?(int)$record['last_used_step']:null);if($step===null)throw new RuntimeException('Invalid or already-used authentication code.');db()->prepare('UPDATE admin_mfa SET last_used_step=?,last_verified_at=NOW() WHERE user_id=?')->execute([$step,$uid]);$_SESSION['admin_mfa_user_id']=$uid;$_SESSION['admin_mfa_verified_at']=time();log_activity($uid,'admin_mfa_verified','user',$uid);redirect('admin/index.php');
  }
  if($action==='enable'){
   if($record)throw new RuntimeException('MFA is already enabled.');$password=(string)($_POST['password']??'');$q=db()->prepare('SELECT password_hash FROM users WHERE id=?');$q->execute([$uid]);if(!password_verify($password,(string)$q->fetchColumn()))throw new RuntimeException('Password confirmation failed.');$secret=(string)($_SESSION['pending_mfa_secret']??'');if($secret==='')throw new RuntimeException('MFA setup session expired. Reload this page.');$step=verify_totp($secret,trim((string)($_POST['code']??'')));if($step===null)throw new RuntimeException('The authenticator code is not valid.');$enc=encrypt_sensitive($secret);$q=db()->prepare('INSERT INTO admin_mfa(user_id,secret_ciphertext,secret_nonce,encryption_alg,enabled_at,last_used_step,last_verified_at) VALUES(?,?,?,?,NOW(),?,NOW())');$q->execute([$uid,$enc['ciphertext'],$enc['nonce'],$enc['alg'],$step]);unset($_SESSION['pending_mfa_secret']);$_SESSION['admin_mfa_user_id']=$uid;$_SESSION['admin_mfa_verified_at']=time();$_SESSION['admin_reauth_user_id']=$uid;$_SESSION['admin_reauth_at']=time();log_activity($uid,'admin_mfa_enabled','user',$uid);flash('success','Admin MFA enabled.');redirect('admin/index.php');
  }
  if($action==='disable'){
   if(env_bool('APP_ADMIN_MFA_REQUIRED',is_production()))throw new RuntimeException('MFA is required by server policy and cannot be disabled.');if(!$record)throw new RuntimeException('MFA is not enabled.');$password=(string)($_POST['password']??'');$q=db()->prepare('SELECT password_hash FROM users WHERE id=?');$q->execute([$uid]);if(!password_verify($password,(string)$q->fetchColumn()))throw new RuntimeException('Password confirmation failed.');$secret=mfa_secret_from_record($record);$step=verify_totp($secret,trim((string)($_POST['code']??'')),isset($record['last_used_step'])?(int)$record['last_used_step']:null);if($step===null)throw new RuntimeException('Invalid authentication code.');db()->prepare('DELETE FROM admin_mfa WHERE user_id=?')->execute([$uid]);unset($_SESSION['admin_mfa_user_id'],$_SESSION['admin_mfa_verified_at'],$_SESSION['admin_reauth_user_id'],$_SESSION['admin_reauth_at']);log_activity($uid,'admin_mfa_disabled','user',$uid);flash('success','Admin MFA disabled.');redirect('admin/mfa.php');
  }
 }catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'MFA operation failed.';security_log('admin_mfa_error',['user_id'=>$uid,'error_class'=>$e::class]);}
}
$record=admin_mfa_record($uid);if(!$record){if(empty($_SESSION['pending_mfa_secret']))$_SESSION['pending_mfa_secret']=base32_encode_secret(random_bytes(20));$secret=(string)$_SESSION['pending_mfa_secret'];$issuer=rawurlencode('LocalConnect');$account=rawurlencode((string)$u['email']);$otpauth="otpauth://totp/{$issuer}:{$account}?secret=".rawurlencode($secret).'&issuer='.$issuer.'&digits=6&period=30';}
$pageTitle='Admin MFA — LocalConnect';require __DIR__.'/../includes/header.php';?>
<div class="container py-5" style="max-width:760px"><h1 class="fw-bold">Admin multi-factor authentication</h1><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><?php if(!$record):?><div class="alert alert-warning">Admin MFA is not enabled. Add the secret below to a TOTP authenticator, then confirm with your password and a current 6-digit code.</div><div class="soft-card p-4 mb-3"><div class="small text-muted">Authenticator secret</div><code class="user-select-all"><?=e($secret)?></code><div class="small text-muted mt-3">Authenticator URI</div><code class="d-block text-break user-select-all"><?=e($otpauth)?></code></div><form method="post" class="soft-card p-4"><?=csrf_field()?><input type="hidden" name="action" value="enable"><label class="form-label">Current password</label><input class="form-control" type="password" name="password" required autocomplete="current-password"><label class="form-label mt-3">6-digit authenticator code</label><input class="form-control" name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required autocomplete="one-time-code"><button class="btn btn-primary mt-3">Enable MFA</button></form><?php elseif(!admin_mfa_verified($u)):?><form method="post" class="soft-card p-4"><?=csrf_field()?><input type="hidden" name="action" value="verify"><p>Enter the current code from your authenticator to continue to the admin panel.</p><input class="form-control" name="code" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" required autofocus autocomplete="one-time-code"><button class="btn btn-primary mt-3">Verify</button></form><?php else:?><div class="alert alert-success">MFA is enabled and verified for this session.</div><?php if(!env_bool('APP_ADMIN_MFA_REQUIRED',is_production())):?><form method="post" class="soft-card p-4"><?=csrf_field()?><input type="hidden" name="action" value="disable"><h4>Disable MFA</h4><p class="text-muted">Requires your password and a fresh authenticator code.</p><input class="form-control mb-2" type="password" name="password" required placeholder="Current password"><input class="form-control" name="code" pattern="[0-9]{6}" maxlength="6" required placeholder="6-digit code"><button class="btn btn-outline-danger mt-3">Disable MFA</button></form><?php endif;?><?php endif;?></div><?php require __DIR__.'/../includes/footer.php';?>
