<?php
declare(strict_types=1);
require_once __DIR__.'/../includes/auth.php';
require_once __DIR__.'/../includes/billing.php';
$admin=require_role('admin');$id=max(0,(int)($_GET['id']??$_POST['id']??0));if($id<=0){http_response_code(404);include __DIR__.'/../404.php';exit;}
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    $admin=require_admin_mfa_for_sensitive();require_recent_admin_reauth('admin/payment-detail.php?id='.$id,600);verify_csrf();
    try{
        $action=(string)($_POST['action']??'');
        if($action==='reconcile_gateway'){reconcile_razorpay_payment($id,'reconciliation',null,(int)$admin['id']);log_activity((int)$admin['id'],'payment_gateway_reconciled','payment',$id,'Server-side gateway reconciliation completed.');flash('success','Gateway payment reconciled.');}
        elseif($action==='approve_manual'){verify_manual_payment_admin($id,(int)$admin['id'],true,(string)($_POST['review_note']??''));flash('success','Manual payment verified and entitlement processed.');}
        elseif($action==='reject_manual'){verify_manual_payment_admin($id,(int)$admin['id'],false,(string)($_POST['review_note']??''));flash('success','Manual payment submission rejected.');}
        else throw new RuntimeException('Unsupported payment action.');
        redirect('admin/payment-detail.php?id='.$id);
    }catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'Payment action failed.';security_log('admin_payment_action_failed',['admin_id'=>(int)$admin['id'],'payment_id'=>$id,'error_class'=>$e::class]);}
}
$q=db()->prepare('SELECT p.*,u.name user_name,u.email,u.role,pm.name current_method_name FROM payments p JOIN users u ON u.id=p.user_id LEFT JOIN payment_methods pm ON pm.id=p.payment_method_id WHERE p.id=? LIMIT 1');$q->execute([$id]);$p=$q->fetch();if(!$p){http_response_code(404);include __DIR__.'/../404.php';exit;}
$q=db()->prepare('SELECT * FROM manual_payment_submissions WHERE payment_id=? LIMIT 1');$q->execute([$id]);$manual=$q->fetch()?:null;
$q=db()->prepare('SELECT h.*,u.name actor_name FROM payment_status_history h LEFT JOIN users u ON u.id=h.actor_user_id WHERE h.payment_id=? ORDER BY h.id DESC LIMIT 100');$q->execute([$id]);$history=$q->fetchAll();
$q=db()->prepare('SELECT * FROM payment_webhook_events WHERE provider_payment_id=? OR provider_order_id=? ORDER BY id DESC LIMIT 100');$q->execute([(string)($p['provider_payment_id']??''),(string)($p['provider_order_id']??'')]);$events=$q->fetchAll();
$pageTitle='Payment #'.$id.' — Admin';require __DIR__.'/../includes/header.php';
?>
<div class="container py-4" style="max-width:1100px"><?php include __DIR__.'/_nav.php';?><div class="d-flex justify-content-between gap-3 align-items-start"><div><h1>Payment #<?=$id?></h1><p class="text-muted"><?=e($p['user_name'])?> · <?=e($p['email'])?> · <?=e($p['role'])?></p></div><a class="btn btn-outline-secondary" href="<?=e(base_url('admin/payments.php'))?>">Back</a></div><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<div class="row g-3 mb-4"><div class="col-lg-7"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Ledger snapshot</h2><dl class="row small"><dt class="col-5">Plan</dt><dd class="col-7"><?=e($p['plan_name_snapshot']??'—')?> (<?=e($p['plan_code_snapshot']??'—')?>)</dd><dt class="col-5">Method</dt><dd class="col-7"><?=e($p['payment_method_name_snapshot']??'—')?> / <?=e($p['payment_method_type_snapshot']??'—')?></dd><dt class="col-5">Subtotal</dt><dd class="col-7">₹<?=number_format((float)($p['subtotal_amount']??$p['amount']),2)?></dd><dt class="col-5">Tax</dt><dd class="col-7">₹<?=number_format((float)($p['tax_amount']??0),2)?></dd><dt class="col-5">Total</dt><dd class="col-7"><strong>₹<?=number_format((float)$p['amount'],2)?> <?=e($p['currency'])?></strong></dd><dt class="col-5">Status</dt><dd class="col-7"><?=e($p['status'])?></dd><dt class="col-5">Reconciliation</dt><dd class="col-7"><?=e($p['reconciliation_status']??'—')?> — <?=e($p['reconciliation_note']??'')?></dd><dt class="col-5">Order ID</dt><dd class="col-7"><code><?=e($p['provider_order_id']??'—')?></code></dd><dt class="col-5">Payment ID</dt><dd class="col-7"><code><?=e($p['provider_payment_id']??'—')?></code></dd><dt class="col-5">Invoice reference</dt><dd class="col-7"><?=e($p['invoice_reference']??'—')?></dd></dl></div></div></div>
<div class="col-lg-5"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5">Reconciliation actions</h2><div class="alert alert-warning small">These actions require admin MFA and a recent password re-authentication. A screenshot/reference alone is never treated as proof.</div><?php if($p['provider']==='razorpay'&&!empty($p['provider_order_id'])&&!empty($p['provider_payment_id'])&&!in_array($p['status'],['refunded','disputed'],true)):?><form method="post" class="mb-3"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="action" value="reconcile_gateway"><button class="btn btn-primary w-100">Reconcile with Razorpay API</button></form><?php endif;?><?php if($manual&&$manual['status']==='pending'):?><div class="mb-2"><strong>Submitted reference:</strong> <?=e($manual['payer_reference'])?></div><div class="small text-muted mb-3"><?=e($manual['payer_note']??'')?></div><form method="post" class="vstack gap-2"><?=csrf_field()?><input type="hidden" name="id" value="<?=$id?>"><textarea class="form-control" name="review_note" maxlength="500" required placeholder="External bank/UPI reconciliation evidence or reason"></textarea><div class="d-flex gap-2"><button class="btn btn-success flex-fill" name="action" value="approve_manual">Verified paid</button><button class="btn btn-outline-danger flex-fill" name="action" value="reject_manual">Reject</button></div></form><?php elseif($manual):?><div class="alert alert-secondary">Manual submission: <?=e($manual['status'])?><?php if($manual['review_note']):?><br><small><?=e($manual['review_note'])?></small><?php endif;?></div><?php endif;?></div></div></div></div>
<h2 class="h4">Status history</h2><div class="card border-0 shadow-sm mb-4"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>When</th><th>From</th><th>To</th><th>Source</th><th>Actor</th><th>Note</th></tr></thead><tbody><?php foreach($history as $h):?><tr><td><?=e($h['created_at'])?></td><td><?=e($h['old_status']??'—')?></td><td><?=e($h['new_status'])?></td><td><?=e($h['source'])?></td><td><?=e($h['actor_name']??'System')?></td><td><?=e($h['note']??'')?></td></tr><?php endforeach;?></tbody></table></div></div>
<h2 class="h4">Webhook receipts</h2><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>When</th><th>Event</th><th>Event key</th><th>Status</th><th>Note</th></tr></thead><tbody><?php if(!$events):?><tr><td colspan="5" class="text-muted text-center py-3">No matching webhook events recorded.</td></tr><?php endif;?><?php foreach($events as $ev):?><tr><td><?=e($ev['received_at'])?></td><td><?=e($ev['event_type'])?></td><td><code><?=e($ev['event_key'])?></code></td><td><?=e($ev['processing_status'])?></td><td><?=e($ev['processing_note']??'')?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<?php require __DIR__.'/../includes/footer.php';?>
