<?php
require_once __DIR__.'/../includes/auth.php';$u=require_role('provider');$uid=(int)$u['id'];
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{$path=upload_image($_FILES['image']??[],'portfolio');if(!$path)throw new RuntimeException('Please choose an image.');$caption=clean_text($_POST['caption']??'',255,false,'Caption');$s=db()->prepare("INSERT INTO portfolio_images(user_id,image_path,caption) VALUES(?,?,?)");$s->execute([$uid,$path,$caption?:null]);flash('success','Work image uploaded.');redirect('provider/portfolio.php');}
    catch(RuntimeException $e){if(isset($path)&&$path)delete_managed_upload($path);$error=$e->getMessage();}
    catch(Throwable $e){if(isset($path)&&$path)delete_managed_upload($path);security_log('portfolio_upload_failed',['error_class'=>$e::class]);$error='Could not save the portfolio image.';}
}
$pg=pagination_window(24,48);$success=flash('success');$s=db()->prepare("SELECT id,image_path,caption,created_at FROM portfolio_images WHERE user_id=? ORDER BY created_at DESC,id DESC LIMIT ".($pg['per']+1)." OFFSET ".$pg['offset']);$s->execute([$uid]);$imgs=$s->fetchAll();$hasNext=trim_page_results($imgs,$pg['per']);release_session_lock();$pageTitle='Portfolio — LocalConnect';require __DIR__.'/../includes/header.php';?>
<div class="container py-5"><h1 class="fw-bold">Work portfolio</h1><p class="text-muted">Upload examples of your own work.</p><?php if($success):?><div class="alert alert-success"><?=e($success)?></div><?php endif;?><?php if(!empty($error)):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><form method="post" enctype="multipart/form-data" class="soft-card p-4 mb-4"><?=csrf_field()?><div class="row g-2"><div class="col-md-5"><input type="file" class="form-control" name="image" required accept="image/jpeg,image/png,image/webp"></div><div class="col-md-5"><input class="form-control" name="caption" maxlength="255" placeholder="Caption"></div><div class="col-md-2 d-grid"><button class="btn btn-primary">Upload</button></div></div></form><div class="row g-3"><?php foreach($imgs as $i):?><div class="col-md-4"><div class="soft-card p-2"><img class="portfolio-img" loading="lazy" src="<?=e(base_url($i['image_path']))?>" alt=""><div class="p-2"><?=e($i['caption']??'Work sample')?></div></div></div><?php endforeach;?></div><?=pagination_nav($pg['page'],$hasNext)?></div><?php require __DIR__.'/../includes/footer.php';?>
